### ISSUE TITLE
Problems with sinatra-authentication after rubygems upgrade...

### ISSUE THREAD

**Issue by abhas** [maxjustus/sinatra-authentication#15]
I just upgraded ruby gems today and now my sinatra application won't start. It fails while loading the sinatra-authentication gem. Is there something that I can do to fix this?

Thanks in advance,

Abhas.

```
/usr/local/ruby/lib/ruby/site_ruby/1.9.1/rubygems.rb:1090:in `escape': can't convert Pathname to String (TypeError)
    from /usr/local/ruby/lib/ruby/site_ruby/1.9.1/rubygems.rb:1090:in `block in loaded_path?'
    from /usr/local/ruby/lib/ruby/site_ruby/1.9.1/rubygems.rb:1089:in `each'
    from /usr/local/ruby/lib/ruby/site_ruby/1.9.1/rubygems.rb:1089:in `find'
    from /usr/local/ruby/lib/ruby/site_ruby/1.9.1/rubygems.rb:1089:in `loaded_path?'
    from /usr/local/ruby/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
    from /usr/local/ruby/lib/ruby/gems/1.9.1/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `block in require'
    from /usr/local/ruby/lib/ruby/gems/1.9.1/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in `block in load_dependency'
    from /usr/local/ruby/lib/ruby/gems/1.9.1/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:596:in `new_constants_in'
    from /usr/local/ruby/lib/ruby/gems/1.9.1/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /usr/local/ruby/lib/ruby/gems/1.9.1/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `require'
    from /usr/local/ruby/lib/ruby/gems/1.9.1/gems/sinatra-authentication-0.4.1/lib/sinatra-authentication.rb:3:in `<top (required)>'
    from /usr/local/ruby/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:57:in `require'
    from /usr/local/ruby/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:57:in `rescue in require'
    from /usr/local/ruby/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
    from /usr/local/ruby/lib/ruby/gems/1.9.1/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `block in require'
    from /usr/local/ruby/lib/ruby/gems/1.9.1/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in `block in load_dependency'
    from /usr/local/ruby/lib/ruby/gems/1.9.1/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:596:in `new_constants_in'
    from /usr/local/ruby/lib/ruby/gems/1.9.1/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /usr/local/ruby/lib/ruby/gems/1.9.1/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `require'
    from index.rb:13:in `<main>'
```

**Comment by abhas** [comment]
I found the problem. Quite a few paths needs to be converted to Strings. I'll do it and send you a pull request.

**Comment by abhas** [comment]
This https://github.com/maxjustus/sinatra-authentication/pull/16 fixes the problem for me.
